name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    if: github.repository == 'MatrosMartz/prtcl'
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup deno
        uses: denoland/setup-deno@v1

      - name: Check files
        run: deno task ok

      - name: Publish to JSR
        run: deno publish
