name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup deno
        run: denoland/setup-deno@1

      - name: Format
        run: deno task fmt:check

      - name: Publish packages
        run: deno publish
